/**
 * Ce que dit chaque action du journal, en clair : partagé par le fil
 * d'activité d'une fiche et par les notifications de ses abonnés.
 */

/** Ce que dit chaque action, en clair. `{piece}` est remplacé par le titre de la pièce. */
export const PHRASES = {
  'marche.cree': 'a créé l’affaire',
  'tache.creee': 'a ajouté une étape au planning',
  'tache.modifiee': 'a mis à jour une étape du planning',
  'tache.terminee': 'a terminé une étape du planning',
  'tache.supprimee': 'a retiré une étape du planning',
  'marche.modifie': 'a modifié la fiche',
  'marche.archive': 'a archivé le marché',
  'marche.desarchive': 'a désarchivé le marché',
  'marche.declare_par_attestation': 'a déclaré l’affaire d’après une attestation',
  'achats.import': 'a importé le classeur des achats',
  'activite.planifiee': 'a planifié une activité',
  'mail.recu': 'a reçu un mail',
  'activite.faite': 'a fait une activité',
  'activite.annulee': 'a annulé une activité',
  'client.cree': 'a créé le client',
  'client.modifie': 'a modifié la fiche',
  'client.contact_ajoute': 'a ajouté un contact',
  'client.contact_modifie': 'a modifié un contact',
  'client.contact_retire': 'a retiré un contact',
  'commande.creee': 'a créé la commande',
  'commande.modifiee': 'a modifié la commande',
  'commande.bon_genere': 'a préparé le bon de commande',
  'commande.envoyee': 'a envoyé le bon de commande au fournisseur',
  'commande.piece_versee': 'a versé une pièce du fournisseur',
  'fournisseur.cree': 'a créé le fournisseur',
  'fournisseur.modifie': 'a modifié la fiche',
  'fournisseur.fusionne': 'a fusionné un doublon dans cette fiche',
  'fournisseur.contact_ajoute': 'a ajouté un contact',
  'fournisseur.contact_modifie': 'a modifié un contact',
  'fournisseur.contact_retire': 'a retiré un contact',
  'document.verse': 'a versé {piece}',
  'document.modifie': 'a rangé ou corrigé {piece}',
  'document.classe_auto': 'a rangé automatiquement {piece}',
  'document.corbeille': 'a mis {piece} en corbeille',
  'document.restaure': 'a restauré {piece}',
  'document.archive': 'a archivé {piece}',
  'document.desarchive': 'a désarchivé {piece}',
  'document.nouvelle_version': 'a déposé une nouvelle version de {piece}',
  'document.relecture': 'a relancé la lecture de {piece}',
  'document.corbeille_lot': 'a mis des pièces en corbeille, dont {piece}',
};
